server:
  port: 80
spring:
  application:
    name: cloud-order-feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka #入驻eureka集群地址

ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 5000


CLOUD-PAYMENT-SERVICE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    #feign日志以什么日志级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug


